const express = require('express')
const app = express()
const cors = require('cors')
const dotenv = require('dotenv').config()
const port = process.env.PORT || 4000
const router = require('./Routes/auth')
const connectDB = require('./koneksi')
app.listen(port,()=>console.log(`Server berjalan pada port ${port}`))
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use('/auth',router)
connectDB()